apiVersion: apps/v1
kind: Deployment
metadata:
    name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: ostart/apigateway:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: apigateway
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8080