apiVersion: apps/v1
kind: Deployment
metadata:
    name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: ostart/authservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__Default
          value: Server=mssql-clusterip-service,1433;Database=Auth;User Id=sa;Password=micR0S3rvice$;TrustServerCertificate=True
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: authservice
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8080